### ISSUE TITLE
Refine the eBPF Interface

### ISSUE THREAD

**Issue by nathanjsweet** [newtools/ebpf#12]
@lmb Thoughts?

**Comment by lmb** [comment]
- Make Map and Program structs and keep some of the metadata passed to New* around for better introspection (cmd/ebpf-test would benefit)
- Get rid of *Instructions since it is equivalent to *[]BPFInstruction and pointers to slices usually aren't necessary (need to double check that)
- Make *Spec regular structs instead of interfaces, and make GetELFSections return a "list of specs" (CollectionSpec? not sure). This will allow users to load from ELF, but then tweak the programs if they desire.
- Add functions to attach an XDP program to a device (separate package?)
- Future: make the map instruction replacement mechanism more generic, so that e.g. constants could be swapped in at runtime. (Might be enough to parse more symbols from ELF)

**Comment by lmb** [comment]
@nathanjsweet what do you think about these suggestions?

**Comment by nathanjsweet** [comment]
This all sounds good. Another one I'd like to add though is pulling test code out of the main build and putting it into a go `_test` file. I can get started on the non XDP stuff if you want.

**Comment by nathanjsweet** [comment]
Create separate issues for each feature for discussion.
